server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.16.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: ${LAVALINK_SERVER_PASSWORD:youshallnotpass}
    sources:
      youtube: false
      http: true
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      nico: false
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      rotation: true
      distortion: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 50
    soundcloudSearchEnabled: true
    soundcloudFilterOutPreviewTracks: true
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
  lavasrc:
    sources:
      yandexmusic: true
    yandexmusic:
      accessToken: ${YANDEX_TOKEN:}
      playlistLoadLimit: 6
      albumLoadLimit: 6
      artistLoadLimit: 6
    # proxy:
    #   url: ${YANDEX_PROXY_URL:}
    #   username: ${YANDEX_PROXY_USERNAME:}
    #   password: ${YANDEX_PROXY_PASSWORD:}

logging:
  level:
    root: INFO
    lavalink: INFO
