server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: ${LAVALINK_SERVER_PASSWORD:youshallnotpass}
    sources:
      youtube: false
      http: true
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      nico: false
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      rotation: true
      distortion: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 50
    soundcloudSearchEnabled: true
    soundcloudFilterOutPreviewTracks: true
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED
  lavasrc:
    sources:
      spotify: true
      yandexmusic: true
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID:}
      clientSecret: ${SPOTIFY_CLIENT_SECRET:}
      countryCode: ${SPOTIFY_MARKET:US}
      preferAnonymousToken: ${SPOTIFY_PREFER_ANONYMOUS_TOKEN:false}
      customTokenEndpoint: ${SPOTIFY_TOKEN_ENDPOINT:http://spotify-tokener:8080/api/token}
      playlistLoadLimit: 20
      albumLoadLimit: 20
      resolveArtistsInSearch: true
      localFiles: false
    yandexmusic:
      accessToken: ${YANDEX_TOKEN:}
      playlistLoadLimit: 6
      albumLoadLimit: 6
      artistLoadLimit: 6

logging:
  level:
    root: INFO
    lavalink: INFO
